version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.18.1
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.18.1
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  tests:
    build: .
    depends_on:
      - selenium-hub
    environment:
      - HUB_URL=http://selenium-hub:4444/wd/hub
    command: mvn clean test -Dheadless=true
